"""Deterministic multi-robot fleet planning and coordination."""

from omokai_fleet.allocation import (
    RouteAssignment,
    RoutePoint,
    partition_route,
    regroup_goals,
)
from omokai_fleet.formation import (
    PLANNED_MINIMUM_DISTANCE_M,
    FormationOffset,
    GoalSeparation,
    formation_goals,
    formation_offsets,
    goal_separations,
    transform_offset,
    validate_goal_separation,
)
from omokai_fleet.lifecycle import (
    LifecycleError,
    PhaseRecord,
    RobotOutcome,
    RobotPhaseResult,
    SquadLifecycle,
    SquadSnapshot,
    SquadState,
)
from omokai_fleet.model import (
    ROBOT_IDS,
    Formation,
    Pose2D,
    Robot,
    RobotGoal,
    RobotId,
    SquadAction,
    SquadPlan,
)
from omokai_fleet.navigation import (
    NavigationBatch,
    NavigationResult,
    NavigationStatus,
    apply_navigation_batch,
)
from omokai_fleet.planner import (
    SQUAD_PLAN_SCHEMA,
    FakeSquadPlanner,
    SquadPlanner,
    SquadPlannerError,
    SquadValidationIssue,
    SquadValidationResult,
    validate_squad_proposal,
)
from omokai_fleet.mission import (
    FleetNavigation,
    SquadMission,
    build_squad_mission,
    execute_squad_mission,
)
from omokai_fleet.separation import (
    EMERGENCY_MINIMUM_DISTANCE_M,
    ObservedRobotPose,
    ObservedSeparation,
    emergency_separation_reason,
    observed_separations,
)

__all__ = [
    'PLANNED_MINIMUM_DISTANCE_M',
    'ROBOT_IDS',
    'Formation',
    'EMERGENCY_MINIMUM_DISTANCE_M',
    'FormationOffset',
    'FakeSquadPlanner',
    'FleetNavigation',
    'GoalSeparation',
    'LifecycleError',
    'NavigationBatch',
    'NavigationResult',
    'NavigationStatus',
    'ObservedRobotPose',
    'ObservedSeparation',
    'PhaseRecord',
    'Pose2D',
    'RouteAssignment',
    'RoutePoint',
    'Robot',
    'RobotGoal',
    'RobotId',
    'RobotOutcome',
    'RobotPhaseResult',
    'SquadAction',
    'SquadLifecycle',
    'SquadMission',
    'SquadPlan',
    'SquadPlanner',
    'SquadPlannerError',
    'SquadValidationIssue',
    'SquadValidationResult',
    'SQUAD_PLAN_SCHEMA',
    'SquadSnapshot',
    'SquadState',
    'formation_goals',
    'formation_offsets',
    'goal_separations',
    'partition_route',
    'regroup_goals',
    'transform_offset',
    'validate_goal_separation',
    'apply_navigation_batch',
    'build_squad_mission',
    'execute_squad_mission',
    'emergency_separation_reason',
    'observed_separations',
    'validate_squad_proposal',
]
